In [ ]:

from processes import eng_to_heb
from main_preprocess import translate_datasets, save_jsonl
from utils.general_functions import read_jsonl_file

In [8]:
aws_trans_destinations_paths = ['____path____/lchaim/datasets/lchaim_aws_dataset/aws_heb_train.json',
                            '____path____/lchaim/datasets/lchaim_aws_dataset/aws_heb_dev.json',
                            '____path____/lchaim/datasets/lchaim_aws_dataset/aws_heb_test.json'
                            ]
''
aws_json_translations_file_path ='____path____/lchaim/aws_control_to_to_heb_core_data/unique_texts_aws_translated.jsonl'
dikta_json_translations_file_path ='____path____/lchaim/aws_control_to_to_heb_core_data/unique_texts.jsonl.dlm2.0translated (1).jsonl'

In [9]:
trans_df = eng_to_heb.get_translation_df(translation_jsonl_path=dikta_json_translations_file_path)

In [10]:
trans_df[trans_df.key == 'text_2851']

,text,key,text_translated,text_len
2851,Fiscal discipline in the United States was thr...,text_2851,המשמעת הפיסקלית בארצות הברית נזרקה לפח האשפה ל...,1038

In [7]:
general_jsons_mapping_pairs_paths = ['../datasets/mapped_datasets/mapped_train.json',
                                     '../datasets/mapped_datasets/mapped_dev.json',
                                     '../datasets/mapped_datasets/mapped_test.json'
                                     ]

dikta_trans_destinations_paths = ['../datasets/lchaim_dikta_dataset/dikta_heb_train.jsonl',
                                  '../datasets/lchaim_dikta_dataset/dikta_heb_dev.jsonl',
                                  '../datasets/lchaim_dikta_dataset/dikta_heb_test.jsonl'
                                  ]
dikta_json_translations_file_path = '../eng_to_heb_processes/unique_texts.jsonl.dlm2.0translated (1).jsonl'


s = translate_datasets(
    jsons_mapping_pairs_paths=general_jsons_mapping_pairs_paths,
    json_translations_file_path=dikta_json_translations_file_path,
    destinations_paths=dikta_trans_destinations_paths,
)

Translating ../datasets/mapped_datasets/mapped_train.json

In [14]:
save_jsonl(s, 'dikta_heb_train.jsonl')

In [22]:
p = '____path____/lchaim/aws_control_to_to_heb_core_data/dikta_heb_train.jsonl'

data = read_jsonl_file(nl_file_path=p, return_df=True)

In [23]:
data

,uid,premise,hypothesis,label
0,id_0,במהלך המאה ה-20 חלו שינויים משמעותיים בתנאי הע...,שיפורים ברפואה הובילו לכך שעובדים מרוויחים יות...,n
1,id_1,במהלך המאה ה-20 חלו שינויים משמעותיים בתנאי הע...,"בשנת 1900, 19% מהנשים בגיל העבודה בצפון אמריקה...",c
2,id_2,במהלך המאה ה-20 חלו שינויים משמעותיים בתנאי הע...,הופעתן של שכונות עוני לאחר שחקלאים עוברים לאזו...,e
3,id_3,במהלך המאה ה-20 חלו שינויים משמעותיים בתנאי הע...,אמריקה ואירופה חלקו את אותן מגמות כלליות בכל ה...,n
4,id_4,במהלך המאה ה-20 חלו שינויים משמעותיים בתנאי הע...,לא נרשמו חסרונות משמעותיים בעקבות שינויים בסבי...,c
...,...,...,...,...
6714,id_6714,שובו של הדשא הנכחד בבריטניה א. זהו הדד של בריט...,בורמיה מקוטעת גדלה באופן גרוע בסביבה חקלאית מו...,e
6715,id_6715,שובו של הדשא הנכחד בבריטניה א. זהו הדד של בריט...,הטבע האנגלי יפעל להחזיר את הברומיום הקטוע בהצל...,c
6716,id_6716,שובו של הדשא הנכחד בבריטניה א. זהו הדד של בריט...,התחייה של הברומין הקטוע מיוחסת יותר למשמעות מד...,e
6717,id_6717,שובו של הדשא הנכחד בבריטניה א. זהו הדד של בריט...,פיליפ סמית בא מאוניברסיטת קיימברידג'.,n
6718,id_6718,שובו של הדשא הנכחד בבריטניה א. זהו הדד של בריט...,ברומית נכחדת שהייתה אמורה להיעלם מהעולם כי לא ...,e

In [24]:
data.to_parquet('check.parquet')

In [25]:
import pandas as pd

In [26]:
pd.read_parquet('check.parquet')

,uid,premise,hypothesis,label
0,id_0,במהלך המאה ה-20 חלו שינויים משמעותיים בתנאי הע...,שיפורים ברפואה הובילו לכך שעובדים מרוויחים יות...,n
1,id_1,במהלך המאה ה-20 חלו שינויים משמעותיים בתנאי הע...,"בשנת 1900, 19% מהנשים בגיל העבודה בצפון אמריקה...",c
2,id_2,במהלך המאה ה-20 חלו שינויים משמעותיים בתנאי הע...,הופעתן של שכונות עוני לאחר שחקלאים עוברים לאזו...,e
3,id_3,במהלך המאה ה-20 חלו שינויים משמעותיים בתנאי הע...,אמריקה ואירופה חלקו את אותן מגמות כלליות בכל ה...,n
4,id_4,במהלך המאה ה-20 חלו שינויים משמעותיים בתנאי הע...,לא נרשמו חסרונות משמעותיים בעקבות שינויים בסבי...,c
...,...,...,...,...
6714,id_6714,שובו של הדשא הנכחד בבריטניה א. זהו הדד של בריט...,בורמיה מקוטעת גדלה באופן גרוע בסביבה חקלאית מו...,e
6715,id_6715,שובו של הדשא הנכחד בבריטניה א. זהו הדד של בריט...,הטבע האנגלי יפעל להחזיר את הברומיום הקטוע בהצל...,c
6716,id_6716,שובו של הדשא הנכחד בבריטניה א. זהו הדד של בריט...,התחייה של הברומין הקטוע מיוחסת יותר למשמעות מד...,e
6717,id_6717,שובו של הדשא הנכחד בבריטניה א. זהו הדד של בריט...,פיליפ סמית בא מאוניברסיטת קיימברידג'.,n
6718,id_6718,שובו של הדשא הנכחד בבריטניה א. זהו הדד של בריט...,ברומית נכחדת שהייתה אמורה להיעלם מהעולם כי לא ...,e